"""add_document_merkle_signing

Revision ID: c081e27bc57a
Revises: f0aae02ae220
Create Date: 2026-08-31 03:10:35.101281
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "c081e27bc57a"
down_revision: str | None = "f0aae02ae220"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("merkle_root", sa.String(length=64), nullable=True))
    op.add_column("documents", sa.Column("merkle_signature", sa.String(length=128), nullable=True))
    op.add_column(
        "documents", sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "last_verified_at")
    op.drop_column("documents", "merkle_signature")
    op.drop_column("documents", "merkle_root")
    # ### end Alembic commands ###
