"""add_field_embeddings

Revision ID: f0aae02ae220
Revises: 0001_core_schema
Create Date: 2026-08-31 01:48:32.128602
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f0aae02ae220'
down_revision: str | None = '0001_core_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_version_id', sa.UUID(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_version_id'], ['field_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_embeddings_field_version_id'), 'field_embeddings', ['field_version_id'], unique=False)
    op.create_index('ix_field_embeddings_version_id', 'field_embeddings', ['field_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_embeddings_version_id', table_name='field_embeddings')
    op.drop_index(op.f('ix_field_embeddings_field_version_id'), table_name='field_embeddings')
    op.drop_table('field_embeddings')
    # ### end Alembic commands ###
